name: Generator

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      use_previous_artifact1:
        type: boolean
        description: "Use previous artifact 1"
        default: false
      use_previous_artifact2:
        type: boolean
        description: "Use previous artifact 2"
        default: false

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "deploy"
  cancel-in-progress: false

jobs:
  download:
    if: ${{ !inputs.use_previous_artifact1 && !inputs.use_previous_artifact2 }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Download OSM notes dump  & Extract
        run: |
          curl -L --fail \
            https://planet.openstreetmap.org/notes/planet-notes-latest.osn.bz2 \
            | bzip2 -dc > planet-notes-latest.osn

      - name: Check size
        run: ls -lh planet-notes-latest.osn

      - name: Run parser
        run: python3 src/parser.py

      - name: Upload notes
        uses: actions/upload-artifact@v7.0.1
        with:
          name: parser-output
          path: |
            notes.bin
          retention-days: 3

  analysis:
    needs: download
    if: ${{ always() && (needs.download.result == 'success' || needs.download.result == 'skipped') && !inputs.use_previous_artifact2 }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Download Artifact
        if: ${{ !inputs.use_previous_artifact1 }}
        uses: actions/download-artifact@v8.0.1
        with:
          name: parser-output

      - name: Download previous artifact
        if: ${{ inputs.use_previous_artifact1 }}
        uses: dawidd6/action-download-artifact@v21
        with:
          workflow: generator.yml
          workflow_conclusion: ""
          branch: main
          name: parser-output
          search_artifacts: true

      - name: Find duplicates
        run: python3 src/generator.py

      - name: Upload duplicates
        uses: actions/upload-artifact@v7.0.1
        with:
          name: dupl-notes
          path: |
            dupl_closed_notes.csv
            dupl_opened_notes.csv
          retention-days: 3

  deploy:
    needs: 
      - analysis
    if: ${{ always() && (needs.analysis.result == 'success' || needs.analysis.result == 'skipped') }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Download duplicates
        if: ${{ !inputs.use_previous_artifact2 }}
        uses: actions/download-artifact@v8.0.1
        with:
          name: dupl-notes

      - name: Download previous artifact
        if: ${{ inputs.use_previous_artifact2 }}
        uses: dawidd6/action-download-artifact@v21
        with:
          workflow: generator.yml
          workflow_conclusion: ""
          branch: main
          name: dupl-notes
          search_artifacts: true

      - name: Download boundaries
        run: curl -L https://osm-countries-geojson.monicz.dev/osm-countries-0-01.geojson.br | brotli -d > osm-countries.geojson

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate pages
        run: python3 src/by_countries.py

      - name: Copy style.css
        run: |
          mkdir -p pages
          cp style.min.css pages/style.css

      - name: HTML Minifier
        uses: docker://devatherock/minify-js:3.1.0
        with:
          directory: 'pages'
          add_suffix: false
          exclusions: |-
            style.css

      - name: Setup Pages
        uses: actions/configure-pages@v6.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: './pages'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

